"""Export saved receiver IQ as native PGFPlots/TikZ (no raster images).

The paper figure has three rows (K=1 UE1, K=2 UE1 and UE2; the row label marks
the weaker and stronger UE of the snapshot channel by ||h_k||^2) and six columns (GNN and the
baseline of the run for each of the three DAC resolutions; IDE with a calibrated
beta for the paper, beta_WF, block beta or WMMSE in earlier runs).
All 4,000 saved fixed-channel samples per panel are retained by default.
All points share one color: like a real (e.g. USRP) receiver, the figure does not
label received samples by their transmitted symbol. The .dat files keep the symbol
label for provenance only.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
DEFAULT_INPUT = HERE / 'exp_results' / 'constellation_16qam_20dB_ide_cal'
DEFAULT_OUTPUT = HERE.parents[2] / 'Quantized-aware-training-and-deploy-study' / 'Figure' / 'constellation_16qam'
PAM = np.array([-3., -1., 1., 3.]) / np.sqrt(10)
LABELS = {'gnn': 'GNN', 'wmmse': 'WMMSE', 'ide_wf': r'IDE, $\beta_{\mathrm{WF}}$',
          'ide_block': r'IDE, block $\beta$', 'ide_cal': r'IDE, calibrated $\beta$'}
POINT_RGB = (0.0, 0.0, 0.0)  # black received samples
# Ideal points: a white cross over a slightly wider black one, visible on the black clusters and on the
# white background alike, also in grayscale. Plain white vanishes off the clusters; red nearly vanishes
# on black in grayscale. The .tex defines both colors once (cqcrosscore, cqcrosshalo).
IDEAL_CORE_RGB, IDEAL_HALO_RGB = (1.0, 1.0, 1.0), (0.0, 0.0, 0.0)


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def figure_tex(panels, layout, compact, notes=None):
    """notes: optional {(K, user): text} added below the row label, e.g. 'weaker'."""
    rows, cols = len(layout), len(layout[0])
    axis_size, horizontal_sep = ('2.30cm', '0.34cm') if compact else ('4.20cm', '0.64cm')
    name = f'cq{rows}x{cols}'
    out = [
        '% Generated by export_constellation_tikz.py from saved rx_equalized IQ.',
        '% Native vector markers: no includegraphics, raster background, jitter or synthetic points.',
        '% Keep the data/ directory beside this source. See tikz_manifest.json for provenance.',
        r'\documentclass[tikz,border=3pt]{standalone}',
        r'\usepackage[T1]{fontenc}',
        r'\usepackage{newtxtext,newtxmath}',
        r'\usepackage{pgfplots}',
        r'\pgfplotsset{compat=1.18}',
        r'\usepgfplotslibrary{groupplots}',
        r'\usetikzlibrary{calc}',
        r'\begin{document}',
        r'\begin{tikzpicture}',
        r'\IfFileExists{Figure/constellation_16qam/data/K1_UE1_b1_gnn.dat}',
        r'  {\def\CQData{Figure/constellation_16qam/data}}',
        r'  {\def\CQData{data}}',
    ]
    rgb = lambda color: ','.join(f'{c:.6f}' for c in color)  # noqa: E731
    out += [r'\definecolor{cqpoint}{rgb}{' + rgb(POINT_RGB) + '}',
            r'\definecolor{cqcrosscore}{rgb}{' + rgb(IDEAL_CORE_RGB) + '}',
            r'\definecolor{cqcrosshalo}{rgb}{' + rgb(IDEAL_HALO_RGB) + '}',
            r'\pgfplotsset{cqpoints/.style={only marks,mark=*,mark size=0.28pt,',
            r'  color=cqpoint,draw=cqpoint,fill=cqpoint,opacity=0.45},',
            r'  cqideal/.style={only marks,mark=x,mark size=1.45pt,forget plot},',
            r'  cqidealhalo/.style={cqideal,color=cqcrosshalo,line width=0.95pt,line cap=round},',
            r'  cqidealcore/.style={cqideal,color=cqcrosscore,line width=0.4pt}}',
            r'\begin{groupplot}[',
            rf'  group style={{group name={name},group size={cols} by {rows},horizontal sep={horizontal_sep},vertical sep=0.55cm}},',
            rf'  scale only axis,width={axis_size},height={axis_size},',
            r'  xmin=-1.8,xmax=1.8,ymin=-1.8,ymax=1.8,',
            r'  xtick={-1,0,1},ytick={-1,0,1},',
            r'  axis lines=box,axis line style={draw=black!55,line width=0.3pt},',
            r'  tick align=outside,tick pos=left,major tick length=1.4pt,',
            r'  tick label style={font=\scriptsize},label style={font=\scriptsize},',
            r'  title style={font=\scriptsize,yshift=-1pt},',
            r'  grid=major,grid style={draw=black!10,line width=0.25pt},',
            r'  clip=true,enlargelimits=false,',
            r']']
    ideal = ' '.join(f'({real:.9f},{imag:.9f})' for real in PAM for imag in PAM)
    annotations = []
    for row, configurations in enumerate(layout):
        for col, key in enumerate(configurations):
            panel = panels[key]
            k, user, bits, method = panel['config']
            options = []
            if row == 0:
                if compact:
                    options.append('title={' + LABELS[method] + '}')
                else:
                    options.append(rf'title={{$b={bits}$ ' + ('bit' if bits == 1 else 'bits') + '}')
            if row == rows - 1:
                options.append('xlabel={In-phase}')
            else:
                options.append('xticklabels={}')
            if col == 0:
                options.append('ylabel={Quadrature}')
            else:
                options.append('yticklabels={}')
            out.append(r'\nextgroupplot[' + ','.join(options) + ']')
            out.append(r'\addplot[cqpoints,forget plot] table[x=I,y=Q] {\CQData/' + key + '.dat};')
            out.append(r'\addplot[cqidealhalo] coordinates {' + ideal + '};')
            out.append(r'\addplot[cqidealcore] coordinates {' + ideal + '};')
            # EVM only: no BER annotation (the paper reports BER over the channel ensemble, fig:tp_ber_16qam).
            evm = panel['evm_rms_percent']
            annotations.append(r'\node[anchor=north west,align=left,font=\tiny,inner sep=1.0pt,fill=white]')
            annotations.append(rf'  at ($({name} c{col+1}r{row+1}.north west)+(0.01cm,-0.01cm)$) {{EVM ' + f'{evm:.1f}' + r'\%};')
    out.append(r'\end{groupplot}')
    out.extend(annotations)
    # Group headings and row labels are attached to finished axis nodes, avoiding clipping.
    if compact:
        for pair, bits in enumerate((1, 2, 3)):
            left, right = 2 * pair + 1, 2 * pair + 2
            out.append(rf'\node[font=\small,anchor=south] at ($({name} c{left}r1.north)!0.5!({name} c{right}r1.north)+(0,0.63cm)$) {{$b={bits}$ bit' + ('s' if bits > 1 else '') + '};')
    for row, configurations in enumerate(layout, 1):
        k, user, _, method = panels[configurations[0]]['config']
        label = rf'$K={k}$\\UE {user}'
        if (notes or {}).get((k, user)):
            label += r'\\(' + notes[k, user] + ')'
        if not compact:
            label += r'\\' + LABELS[method]
        out.append(rf'\node[anchor=east,align=center,font=\scriptsize] at ($({name} c1r{row}.west)+(-1.20cm,0)$) {{{label}}};')
    out += [r'\end{tikzpicture}', r'\end{document}', '']
    return '\n'.join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input-dir', type=Path, default=DEFAULT_INPUT)
    parser.add_argument('--output-dir', type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    root, out = args.input_dir.resolve(), args.output_dir.resolve()
    metadata = json.loads((root / 'metadata.json').read_text())
    if metadata['users'] != [1, 2] or metadata['bits'] != [1, 2, 3]:
        raise ValueError('The paper layout requires K=1,2 and DAC bits=1,2,3')
    # Runs made before the baseline became selectable have no 'methods' entry.
    methods = tuple(metadata.get('methods', ('gnn', 'wmmse')))
    summary = json.loads((root / 'summary.json').read_text())
    metrics = {(r['K'], r['user'], r['bits'], r['method']): r
               for r in summary['results'] if r['scope'] == 'snapshot'}
    data_dir = out / 'data'
    data_dir.mkdir(parents=True, exist_ok=True)
    panels, sources, weaker = {}, {}, {}
    for k in (1, 2):
        shared_file = root / f'shared_K{k}.npz'
        sources[shared_file.name] = sha256(shared_file)
        with np.load(shared_file, allow_pickle=False) as shared:
            start = int(shared['n_eval'])
            s = shared['tx_symbols'][start:]
            channel_ids = shared['channel_indices'][start:]
            # the weaker UE of the snapshot channel: the smaller ||h_k||^2 (a channel property, same for all methods)
            weaker[k] = int(np.argmin((np.abs(shared['H'][start]) ** 2).sum(0))) + 1
        if not len(s) or not np.all(channel_ids == metadata['snapshot_channel_index']):
            raise ValueError('Expected saved fixed-channel snapshot blocks')
        for bits in (1, 2, 3):
            for method in methods:
                source = root / f'K{k}_b{bits}_{method}.npz'
                sources[source.name] = sha256(source)
                with np.load(source, allow_pickle=False) as saved:
                    received = saved['rx_equalized'][start:]
                for user in range(1, k + 1):
                    z, reference = received[:, user-1].ravel(), s[:, user-1].ravel()
                    real_ids = np.abs(reference.real[:, None] - PAM).argmin(-1)
                    imag_ids = np.abs(reference.imag[:, None] - PAM).argmin(-1)
                    labels = real_ids * 4 + imag_ids
                    key = f'K{k}_UE{user}_b{bits}_{method}'
                    path = data_dir / (key + '.dat')
                    table = np.column_stack((z.real, z.imag, labels, np.arange(len(z))))
                    np.savetxt(path, table, header='I Q symbol sample_index', comments='',
                               fmt=['%.9g', '%.9g', '%d', '%d'])
                    # Verify the actual serialized plotting data, not just the source arrays.
                    restored = np.loadtxt(path, skiprows=1)
                    if not np.array_equal(restored[:, :2].astype(np.float32), table[:, :2].astype(np.float32)):
                        raise AssertionError('IQ export lost float32 precision')
                    if not np.array_equal(restored[:, 2:], table[:, 2:]):
                        raise AssertionError('IQ export changed labels or sample ordering')
                    record = metrics[k, user, bits, method]
                    panels[key] = {'config': [k, user, bits, method], 'symbols': len(z),
                                   'evm_rms_percent': record['evm_rms_percent'], 'ber_mc': record['ber_mc'],
                                   'source': source.name, 'array': 'rx_equalized', 'start_block': start,
                                   'user_axis': user - 1, 'dat_sha256': sha256(path)}
    # Paper figure: the single UE for K = 1 and both UEs for K = 2, labelled weaker / stronger (||h_k||^2).
    combined = [[f'K{k}_UE{u}_b{b}_{m}' for b in (1, 2, 3) for m in methods]
                for k, u in ((1, 1), (2, 1), (2, 2))]
    notes = {(2, weaker[2]): 'weaker', (2, 3 - weaker[2]): 'stronger'}
    layouts = {
        'constellation_16qam_tikz': (combined, True),
        'constellation_K1_tikz': ([[f'K1_UE1_b{b}_{m}' for b in (1,2,3)] for m in methods], False),
        'constellation_K2_tikz': ([[f'K2_UE{u}_b{b}_{m}' for b in (1,2,3)] for u in (1,2) for m in methods], False),
    }
    for name, (layout, compact) in layouts.items():
        destination = out / (name + '.tex')
        destination.write_text(figure_tex(panels, layout, compact, notes))
        print(destination)
    manifest = {'source_directory': str(root), 'source_sha256': sources,
                'generator': str(Path(__file__).resolve()), 'generator_sha256': sha256(Path(__file__)),
                'snapshot_channel_index': metadata['snapshot_channel_index'], 'snr_db': metadata['snr_db'],
                'methods': list(methods),
                'paper_rows': 'K=1 UE1; K=2 UE1 and UE2, labelled weaker/stronger by ||h_k||^2 of the snapshot channel',
                'weaker_ue': {str(k): u for k, u in weaker.items()},
                'oracle_block_gain': True, 'subsampling': False,
                'iq_export_float32_roundtrip': 'exact for every saved plotted I/Q value',
                'point_color': 'single color (black, opacity 0.45); no per-symbol coloring, as at a real receiver',
                'ideal_points': 'white cross (0.4 pt) over a black cross (0.95 pt), mark size 1.45 pt',
                'symbol_column': '4*I_level_index+Q_level_index, [-3,-1,1,3]/sqrt(10); provenance only, not plotted',
                'panels': panels, 'figures': list(layouts)}
    (out / 'tikz_manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    print(f'Exported {len(panels)} panels, {sum(p["symbols"] for p in panels.values())} actual IQ points.')


if __name__ == '__main__':
    main()
