"""Figure of Sec. VI-A (residual inter-AP phase offsets) from exp_results/phase_offset_eval.json, in the style of
Rsum_sweep_vs_snr (plot_continue_figures.py): K = 2, the configuration of the over-the-air experiment. Baseline: IDE
with calibrated beta (BASE; the earlier version showed WMMSE + DAC, 'wmmse_dac', which stays in the json), reference:
unquantized WMMSE.

  (a) mean sum rate at 20 dB vs sigma_theta: Monte Carlo (markers) and the kappa model of eq. (tp_kappa) (lines)
  (b) standard deviation over the offset draws for a fixed channel, sqrt(E_H[Var_theta(R | H)]), at 20 dB
  (c) relative sum-rate loss vs SNR at sigma_theta = 20 deg, 1 - R(20 deg) / R(0)

  python plot_phase_offset.py [out.tex]     # default: the paper's Figure/rsum_phase_offset.tex
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'exp_results', 'phase_offset_eval.json')
OUT = '/home/user/Quantized-aware-training-and-deploy-study/Figure/rsum_phase_offset.tex'
K = 2
SNR_A = 20.0
SIGMA_C = 20.0
BASE, BASE_TXT = 'ide_cal', r'IDE, calibrated $\beta$'

HEAD = r"""% Sum rate under residual inter-AP carrier phase offsets theta_m ~ N(0, sigma_theta^2), i.i.d. over the APs,
% constant over a block and unknown to the precoder (Sec. VI-A); M = 40, K = 2; precoders trained with sigma_theta = 0.
% (a) mean sum rate at 20 dB vs sigma_theta: markers = Monte Carlo, lines = kappa model of eq. (tp_kappa)
%     (offset-averaged signal, interference and distortion powers).
% (b) standard deviation of the sum rate over the offset draws for a fixed channel, sqrt(E_H[Var_theta(R | H)]),
%     at 20 dB.
% (c) relative loss 1 - R(sigma_theta = 20 deg) / R(0) vs SNR.
% Colors as in Rsum_sweep_vs_snr: b = 1/2/3 -> blue/teal/vermilion, circle/square/triangle; GNN saturated and solid,
% IDE with calibrated beta (Wang et al., TWC 2018; beta calibrated per channel and SNR on an independent block of 125
% Gaussian symbol vectors) muted and dash-dotted, unquantized WMMSE dark.
% Data: exp_results/phase_offset_eval.json (phase_offset_eval.py): 2048 held-out channels (Htest[4096:6144]),
% {n} offset draws per channel, LS Bussgang estimator; sigma_theta = 0 reproduces Figs. 3 and 4.
% Generated by plot_phase_offset.py.
\documentclass[tikz,border=4pt]{{standalone}}
\usepackage[T1]{{fontenc}}
\usepackage{{newtxtext,newtxmath}}
\usepackage{{pgfplots}}
\pgfplotsset{{compat=1.18}}
\usepgfplotslibrary{{groupplots}}
\usetikzlibrary{{calc}}
\begin{{document}}
\definecolor{{snrOne}}{{HTML}}{{0072B2}}
\definecolor{{snrTwo}}{{HTML}}{{009E73}}
\definecolor{{snrThree}}{{HTML}}{{D55E00}}
\definecolor{{snrMuted}}{{HTML}}{{9BA3AB}}
\definecolor{{snrGrid}}{{HTML}}{{E2E5E8}}
\definecolor{{snrInk}}{{HTML}}{{42484F}}
\begin{{tikzpicture}}
\pgfplotsset{{
  po/gnn/.style={{solid, line width=1.1pt, mark options={{solid}}, forget plot}},
  po/base/.style={{dash dot, line width=0.85pt, mark options={{solid, fill=white, line width=0.75pt}}, forget plot}},
  po/unq/.style={{solid, line width=0.9pt, forget plot}},
  po/mc/.style={{only marks, forget plot}},
  po/model/.style={{mark=none, forget plot}},
  po/one/.style={{mark=*, mark size=1.85pt}},
  po/two/.style={{mark=square*, mark size=1.8pt}},
  po/three/.style={{mark=triangle*, mark size=2.4pt}},
  po/unqmark/.style={{mark=diamond*, mark size=2.3pt}},
}}
\begin{{groupplot}}[
  group style={{group name=po, group size=3 by 1, horizontal sep=1.45cm}},
  scale only axis, width=4.55cm, height=4.4cm,
  axis lines=left, axis line style={{draw=snrInk, line width=0.45pt, -}},
  tick align=outside, tick pos=left,
  major tick length=2.5pt, tick style={{draw=snrInk, line width=0.45pt}},
  ymajorgrids=true, xmajorgrids=false,
  grid style={{line width=0.3pt, draw=snrGrid}},
  every axis plot/.append style={{line join=round}},
  title style={{font=\small, yshift=2pt}},
  tick label style={{font=\footnotesize, /pgf/number format/fixed}},
  label style={{font=\small}},
]
"""
BCOL = {1: 'snrOne', 2: 'snrTwo', 3: 'snrThree'}
BSTY = {1: 'one', 2: 'two', 3: 'three'}
BTXT = {1: '1 bit', 2: '2 bits', 3: '3 bits'}


def table(xs, ys):
    return 'table {%\n' + '\n'.join(f'{x:g} {y:.4f}' for x, y in zip(xs, ys)) + '\n};'


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else OUT
    J = json.load(open(SRC))
    S, X = J['sigma_deg'], J['snr_db']
    ja, ic = X.index(SNR_A), S.index(SIGMA_C)
    R = {b: J['results'][f'K{K}b{b}']['methods'] for b in (1, 2, 3)}

    def col(b, m, k, j):          # [sigma] at SNR index j
        return [row[j] for row in R[b][m][k]]

    def loss(b, m):               # [snr] at sigma index ic, percent
        mu = R[b][m]['mean']
        return [100 * (1 - mu[ic][j] / mu[0][j]) for j in range(len(X))]

    L = [HEAD.format(n=J['n_theta']).rstrip('\n')]

    # (a) mean at 20 dB
    ymax_a = 5 * (int(max(max(col(b, 'wmmse_unq', 'mean', ja)) for b in (1, 2, 3)) / 5) + 1)
    L.append(r'\nextgroupplot[' + '\n  ' + ',\n  '.join([
        r'title={(a) Mean sum rate, SNR $=20$\,dB}', r'xlabel={$\sigma_\theta$ [deg]}',
        r'ylabel={$R_{\mathrm{sum}}$ [bits/channel use]}', 'xmin=-1.5, xmax=31.5, xtick={0,10,20,30}',
        f'ymin=0, ymax={ymax_a}', 'legend to name=polegend', 'legend columns=4', 'legend cell align=left',
        'legend style={\n    draw=none, fill=none, font=\\footnotesize,\n'
        '    /tikz/every even column/.append style={column sep=0.5cm},\n  }']) + ',\n]')
    for b in (1, 2, 3):
        L += [r'\addlegendimage{%s, po/gnn, po/%s}' % (BCOL[b], BSTY[b]), r'\addlegendentry{GNN, %s}' % BTXT[b]]
    L += [r'\addlegendimage{snrInk, po/unq, po/unqmark}', r'\addlegendentry{Unquantized WMMSE}']
    for b in (1, 2, 3):
        L += [r'\addlegendimage{%s!55!snrMuted, po/base, po/%s}' % (BCOL[b], BSTY[b]),
              r'\addlegendentry{%s, %s}' % (BASE_TXT, BTXT[b])]
    L += [r'\node[anchor=south west, font=\scriptsize, text=snrInk, align=left] at (rel axis cs:0.03,0.03)',
          r'  {markers: Monte Carlo\\lines: $\kappa$ model};']
    L.append(r'\addplot[snrInk, po/unq, po/model] ' + table(S, col(1, 'wmmse_unq', 'kappa', ja)))
    L.append(r'\addplot[snrInk, po/unq, po/mc, po/unqmark] ' + table(S, col(1, 'wmmse_unq', 'mean', ja)))
    for b in (1, 2, 3):
        L.append(r'\addplot[%s!55!snrMuted, po/base, po/model] %s' % (BCOL[b], table(S, col(b, BASE, 'kappa', ja))))
        L.append(r'\addplot[%s!55!snrMuted, po/base, po/mc, po/%s] %s' % (BCOL[b], BSTY[b], table(S, col(b, BASE, 'mean', ja))))
    for b in (1, 2, 3):
        L.append(r'\addplot[%s, po/gnn, po/model] %s' % (BCOL[b], table(S, col(b, 'gnn', 'kappa', ja))))
        L.append(r'\addplot[%s, po/gnn, po/mc, po/%s] %s' % (BCOL[b], BSTY[b], table(S, col(b, 'gnn', 'mean', ja))))

    # (b) std over the offsets at 20 dB
    L.append(r'\nextgroupplot[title={(b) Std.\ dev.\ over offsets, SNR $=20$\,dB}, xlabel={$\sigma_\theta$ [deg]}, '
             r'ylabel={Std.\ dev.\ of $R_{\mathrm{sum}}$ [bits/channel use]}, '
             r'xmin=-1.5, xmax=31.5, xtick={0,10,20,30}, ymin=0]')
    L.append(r'\addplot[snrInk, po/unq, po/unqmark] ' + table(S, col(1, 'wmmse_unq', 'std_offset', ja)))
    for b in (1, 2, 3):
        L.append(r'\addplot[%s!55!snrMuted, po/base, po/%s] %s' % (BCOL[b], BSTY[b], table(S, col(b, BASE, 'std_offset', ja))))
    for b in (1, 2, 3):
        L.append(r'\addplot[%s, po/gnn, po/%s] %s' % (BCOL[b], BSTY[b], table(S, col(b, 'gnn', 'std_offset', ja))))

    # (c) relative loss vs SNR at sigma_theta = 20 deg
    L.append(r'\nextgroupplot[title={(c) Relative loss, $\sigma_\theta=%g^\circ$}, xlabel={SNR [dB]}, '
             r'ylabel={Relative loss [\%%]}, '
             r'xmin=-12, xmax=32, xtick={-10,0,10,20,30}, ymin=0]' % SIGMA_C)
    L.append(r'\addplot[snrInk, po/unq, po/unqmark, mark repeat=2, mark phase=1] ' + table(X, loss(1, 'wmmse_unq')))
    for b in (1, 2, 3):
        L.append(r'\addplot[%s!55!snrMuted, po/base, po/%s, mark repeat=2, mark phase=1] %s'
                 % (BCOL[b], BSTY[b], table(X, loss(b, BASE))))
    for b in (1, 2, 3):
        L.append(r'\addplot[%s, po/gnn, po/%s, mark repeat=2, mark phase=1] %s' % (BCOL[b], BSTY[b], table(X, loss(b, 'gnn'))))

    L += [r'\end{groupplot}', r'\node[anchor=south] at ($(po c2r1.north)+(0,0.65cm)$)',
          r'  {\pgfplotslegendfromname{polegend}};', r'\end{tikzpicture}', r'\end{document}', '']
    open(out, 'w').write('\n'.join(L))
    print('wrote', out)


if __name__ == '__main__':
    main()
