"""Regenerate stored_models_cellfree_sweep_continue/Rsum_sweep_vs_{bits,snr}.tex from the result files, in
the hand-tuned style those two figures already had (colors, line styles, layout and notes are kept),
with the continued models and the WMMSE baselines added.

Data (all rates: LS Bussgang estimator, test set [4096:6144], 125 symbols per channel):
  GNN, GNN-GD, ZF/MRT + DAC, unquantized ZF/MRT
      K >= 2 and K = 1, b = 2/3: stored_models_cellfree_sweep_continue/<run>/snr_curves.json
                                 (continue_sweep_training.py, 15 + 15 epochs; GNN-GD recomputed from
                                 each continued model)
      K = 1, b = 1:              stored_models_cellfree_k1_continue/<run>_cosine/ (continue_k1_training.py,
                                 20 + 20 epochs): snr_curves_ls.json ('gnn') and gnn_gd_curves.json
                                 (GNN-GD of this model); MRT baselines from the sweep folder
  WMMSE, unquantized and + b-bit DAC: <sweep run>/wmmse_curves.json (wmmse_baseline.py). The DAC
      convention is 'equal' -- per-AP normalization, no de-normalization, every AP at the same power --
      the convention of the ZF + DAC baseline and the constraint the GNN works under. For K = 1 WMMSE
      reduces to MRT, so its markers would coincide with MRT's and are not drawn.
Also writes preview_continue_figures.png (matplotlib twin; no TeX on this machine).

  python plot_continue_figures.py
"""
import glob
import json
import os

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
SWEEP = os.path.join(HERE, 'stored_models_cellfree_sweep_K_bits')
CONT = os.path.join(HERE, 'stored_models_cellfree_sweep_continue')
K1CONT = glob.glob(os.path.join(HERE, 'stored_models_cellfree_k1_continue', '*_ep20to40_cosine'))[0]
SNR = [float(x) for x in range(-30, 31, 5)]
I20 = SNR.index(20.0)
SNR_PLOT = [x for x in SNR if x >= -10]
LS_NOTE = 'unbiased least-squares Bussgang estimator, G = (sum y s^H)(sum s s^H)^-1 (see eq:tp_G_hat)'


def one(pattern):
    ds = glob.glob(pattern)
    assert len(ds) == 1, (pattern, ds)
    return ds[0]


def load():
    data = {}
    for K in (1, 2, 4, 6):
        for b in (1, 2, 3):
            if (K, b) == (1, 1):
                src = one(os.path.join(SWEEP, 'M_40_K_1_1bit_*'))
                s = json.load(open(os.path.join(src, 'snr_curves.json')))
                c = json.load(open(os.path.join(K1CONT, 'snr_curves_ls.json')))
                g = json.load(open(os.path.join(K1CONT, 'gnn_gd_curves.json')))
                assert max(abs(x - y) for x, y in zip(g['gnn'], c['gnn'])) < 1e-3   # GNN-GD started from this model
                d = {'gnn': c['gnn'], 'gd': g['gnn_gd'], 'lin_q': s['mrt_1bit'], 'lin_unq': s['mrt_unquantized']}
            else:
                src = one(os.path.join(SWEEP, f'M40_K{K}_b{b}_ep15_*'))
                c = json.load(open(one(os.path.join(CONT, f'M40_K{K}_b{b}_*', 'snr_curves.json'))))
                d = {'gnn': c['gnn'], 'gd': c['gnn_gd'], 'lin_q': c['linear_quantized'],
                     'lin_unq': c['linear_unquantized']}
            w = json.load(open(os.path.join(src, 'wmmse_curves.json')))
            assert w['snr_db'] == SNR and max(abs(x - y) for x, y in zip(w['lin_q_equal'], d['lin_q'])) < 1e-3
            d.update(wmmse_q=w['wmmse_quantized_equal'], wmmse_unq=w['wmmse_unquantized'])
            data[(K, b)] = d
    return data


# ------------------------------------------------------------------------------------------ fig: bits
BITS_HEAD = r"""% Sum rate at SNR = 20.0 dB vs DAC resolution, after continued training.
% Two panels: K = 1, 2 on the left; K = 4, 6 on the right.
% Color identifies K; line style and marker identify the method.
% The panels use different y-axis ranges, both starting at zero.
% Unquantized ZF/MRT and unquantized WMMSE are separate references at the categorical infinity tick,
% drawn side by side (ZF/MRT left, WMMSE right of the tick); no extrapolation is drawn.
% GNN: best epoch of the continued runs -- K = 1, b = 1: continue_k1_training.py (20 + 20 epochs, cosine
%   1e-3 -> 5e-5); every other (K, b): continue_sweep_training.py (15 + 15 epochs, cosine 2e-4 -> 1e-5).
% GNN-GD: each continued GNN's output refined per channel by gd_baseline.gd_optimize (200 Adam steps,
%   Opt-GNN budget of arXiv:2606.23141, recipe not re-tuned per (K, b)); gnn_gd >= gnn channel by channel.
% WMMSE: sum-rate WMMSE (wmmse_baseline.py), per channel and per SNR. + DAC: per-AP normalization, nearest
%   b-bit level, no de-normalization (every AP at the same power), as ZF/MRT + DAC and as the GNN.
%   For K = 1 WMMSE reduces to MRT; its markers would coincide with MRT's and are not drawn.
% Rates: {ls}
% Generated by plot_continue_figures.py.
\documentclass[tikz,border=4pt]{{standalone}}
\usepackage[T1]{{fontenc}}
\usepackage{{newtxtext,newtxmath}}
\usepackage{{pgfplots}}
\pgfplotsset{{compat=1.18}}
\usepgfplotslibrary{{groupplots}}
\usetikzlibrary{{calc}}
\begin{{document}}
\definecolor{{rsumKone}}{{HTML}}{{0072B2}}
\definecolor{{rsumKtwo}}{{HTML}}{{D55E00}}
\definecolor{{rsumKfour}}{{HTML}}{{009E73}}
\definecolor{{rsumKsix}}{{HTML}}{{A35D94}}
\definecolor{{rsumGrid}}{{HTML}}{{E2E5E8}}
\definecolor{{rsumInk}}{{HTML}}{{42484F}}
"""

BITS_STYLES = r"""
\begin{tikzpicture}
\pgfplotsset{
  rsum bits/gnn/.style={
    solid, line width=1.05pt, mark=*, mark size=2.1pt,
    mark options={solid}, forget plot,
  },
  rsum bits/gd/.style={
    dashed, line width=1.05pt, mark=triangle*, mark size=2.7pt,
    mark options={solid, fill=white}, forget plot,
  },
  rsum bits/wmmse/.style={
    dash dot, line width=1.05pt, mark=pentagon*, mark size=2.3pt,
    mark options={solid, fill=white}, forget plot,
  },
  rsum bits/linear/.style={
    densely dotted, line width=1.05pt, mark=square*, mark size=2.0pt,
    mark options={solid, fill=white}, forget plot,
  },
  rsum bits/unquantized/.style={
    only marks, mark=diamond*, mark size=3.0pt,
    mark options={solid}, forget plot,
  },
  rsum bits/unquantized wmmse/.style={
    only marks, mark=pentagon*, mark size=2.8pt,
    mark options={solid}, forget plot,
  },
}
\begin{groupplot}[
  group style={group name=rsumbits, group size=2 by 1, horizontal sep=1.35cm},
  scale only axis, width=7.2cm, height=5.1cm,
  axis lines=left, axis line style={draw=rsumInk, line width=0.45pt, -},
  tick align=outside, tick pos=left,
  major tick length=2.5pt, tick style={draw=rsumInk, line width=0.45pt},
  ymajorgrids=true, xmajorgrids=false,
  grid style={line width=0.3pt, draw=rsumGrid},
  every axis plot/.append style={line join=round},
  title style={font=\small, yshift=2pt},
  tick label style={font=\footnotesize, /pgf/number format/fixed},
  label style={font=\small},
  xmin=0.8, xmax=4.65, xtick={1,2,3,4.2},
  xticklabels={1,2,3,$\infty$},
  xlabel={DAC resolution $b$ [bits]},
  ylabel={$R_{\mathrm{sum}}$ [bits/channel use]},
  ymin=0,
]
"""

KCOL = {1: 'rsumKone', 2: 'rsumKtwo', 4: 'rsumKfour', 6: 'rsumKsix'}
KNAME = {1: 'One', 2: 'Two', 4: 'Four', 6: 'Six'}
X_UNQ_LIN, X_UNQ_WMMSE = 4.05, 4.35


def bits_tables(data):
    L = ['% Measurements at 20 dB, stored once per (K, b, method).']
    for K in (1, 2, 4, 6):
        cols = ['b', 'gnn', 'gd', 'linear'] + (['wmmse'] if K > 1 else [])
        L.append(r'\pgfplotstableread{')
        L.append(' '.join(cols))
        for b in (1, 2, 3):
            d = data[(K, b)]
            row = [str(b), f"{d['gnn'][I20]:.4f}", f"{d['gd'][I20]:.4f}", f"{d['lin_q'][I20]:.4f}"]
            if K > 1:
                row.append(f"{d['wmmse_q'][I20]:.4f}")
            L.append(' '.join(row))
        L.append(r'}\rsumBits' + KNAME[K])
    return '\n'.join(L)


def bits_panel(data, Ks, title, ymax, yticks, first):
    L = []
    opts = [f'title={{{title}}}', f'ymax={ymax}', 'ytick={' + ','.join(map(str, yticks)) + '}']
    if first:
        opts += ['legend to name=rsumbitslegend', 'legend columns=3', 'legend cell align=left',
                 'legend style={\n    draw=none, fill=none, font=\\footnotesize,\n'
                 '    /tikz/every even column/.append style={column sep=0.45cm},\n  }']
    L.append(r'\nextgroupplot[' + '\n  ' + ',\n  '.join(opts) + ',\n]')
    if first:   # row-wise fill: columns = learned | quantized linear | unquantized
        for sty, name in (('gnn', 'GNN'), ('wmmse', 'WMMSE + DAC'), ('unquantized wmmse', 'Unquantized WMMSE'),
                          ('gd', 'GNN-GD'), ('linear', 'ZF/MRT + DAC'), ('unquantized', 'Unquantized ZF/MRT')):
            L += [r'\addlegendimage{rsumInk, rsum bits/%s}' % sty, r'\addlegendentry{%s}' % name]
        L.append('')
    L += ['% The shaded strip is a reference category, not a finite bit interval.',
          r'\path[fill=black!3] (axis cs:3.65,0) rectangle (axis cs:4.65,%s);' % ymax,
          r'\draw[black!22, densely dashed, line width=0.4pt]',
          r'  (axis cs:3.65,0) -- (axis cs:3.65,%s);' % ymax]
    for sty, col in (('linear', 'linear'), ('wmmse', 'wmmse'), ('gnn', 'gnn'), ('gd', 'gd')):
        for K in Ks:
            if col == 'wmmse' and K == 1:
                continue
            L.append(r'\addplot[%s, rsum bits/%s] table[x=b,y=%s] {\rsumBits%s};' % (KCOL[K], sty, col, KNAME[K]))
    for K in Ks:
        d = data[(K, 1)]
        L.append(r'\addplot[%s, rsum bits/unquantized] coordinates {(%g,%.4f)};' % (KCOL[K], X_UNQ_LIN, d['lin_unq'][I20]))
        if K > 1:
            L.append(r'\addplot[%s, rsum bits/unquantized wmmse] coordinates {(%g,%.4f)};'
                     % (KCOL[K], X_UNQ_WMMSE, d['wmmse_unq'][I20]))
    for K in Ks:   # line-end labels next to the highest curve at b = 3 (GNN-GD)
        L += [r'\node[anchor=west, font=\footnotesize, text=%s, xshift=4pt]' % KCOL[K],
              r'  at (axis cs:3,%.4f) {$K=%d$};' % (data[(K, 3)]['gd'][I20], K)]
    for K in Ks:   # reference labels above the higher of the two markers
        d = data[(K, 1)]
        top = max(d['lin_unq'][I20], d['wmmse_unq'][I20]) if K > 1 else d['lin_unq'][I20]
        x = 4.2 if K > 1 else X_UNQ_LIN
        L += [r'\node[anchor=south, font=\scriptsize, text=%s, yshift=3pt]' % KCOL[K],
              r'  at (axis cs:%g,%.4f) {$K=%d$};' % (x, top, K)]
    if 1 in Ks:
        L.append(r'\node[anchor=north west, font=\scriptsize, text=rsumInk, align=left] at (rel axis cs:0.02,0.98)'
                 r' {$K=1$: WMMSE $\equiv$ MRT};')
    return '\n'.join(L)


def fig_bits(data, out):
    body = [BITS_HEAD.format(ls=LS_NOTE), bits_tables(data), BITS_STYLES,
            bits_panel(data, (1, 2), '(a) $K=1,2$', 21, [0, 5, 10, 15, 20], True), '',
            bits_panel(data, (4, 6), '(b) $K=4,6$', 51, [0, 10, 20, 30, 40, 50], False),
            r'\end{groupplot}', r'\node[anchor=south] at',
            r'  ($(rsumbits c1r1.north)!0.5!(rsumbits c2r1.north)+(0,0.65cm)$)',
            r'  {\pgfplotslegendfromname{rsumbitslegend}};', r'\end{tikzpicture}', r'\end{document}', '']
    open(out, 'w').write('\n'.join(body))


# ------------------------------------------------------------------------------------------- fig: SNR
SNR_HEAD = r"""% Sum rate vs SNR for K = 2, 4, 6 (K = 1 is shown separately in fig:tp_rsum_M40K1), after continued training.
% One panel per K; all y-axes start at zero and use separate ranges, sized to show the whole unquantized
% WMMSE curve.
% b = 1/2/3 -> blue/teal/vermilion and circle/square/triangle.
% GNN: saturated solid lines and filled markers (best epoch of continue_sweep_training.py, 15 + 15 epochs).
% ZF + DAC: muted dashed lines and open markers in the matching bit color.
% WMMSE + DAC: muted dash-dotted lines without markers in the matching bit color (per-AP normalization,
%   nearest b-bit level, no de-normalization -- the DAC model of ZF + DAC and of the GNN).
% Unquantized WMMSE: dark solid line (sum-rate WMMSE per channel and SNR, wmmse_baseline.py); one curve
%   per K, independent of b.
% All nine samples per curve are retained; markers appear every other sample.
% Rates: {ls}
% Generated by plot_continue_figures.py.
\documentclass[tikz,border=4pt]{{standalone}}
\usepackage[T1]{{fontenc}}
\usepackage{{newtxtext,newtxmath}}
\usepackage{{pgfplots}}
\pgfplotsset{{compat=1.18}}
\usepgfplotslibrary{{groupplots}}
\usetikzlibrary{{calc}}
\begin{{document}}
\definecolor{{snrOne}}{{HTML}}{{0072B2}}
\definecolor{{snrTwo}}{{HTML}}{{009E73}}
\definecolor{{snrThree}}{{HTML}}{{D55E00}}
\definecolor{{snrMuted}}{{HTML}}{{9BA3AB}}
\definecolor{{snrGrid}}{{HTML}}{{E2E5E8}}
\definecolor{{snrInk}}{{HTML}}{{42484F}}
\begin{{tikzpicture}}
\pgfplotsset{{
  rsum snr/gnn/.style={{
    solid, line width=1.1pt, mark options={{solid}}, forget plot,
  }},
  rsum snr/zf/.style={{
    dashed, line width=0.85pt,
    mark options={{solid, fill=white, line width=0.75pt}}, forget plot,
  }},
  rsum snr/wmmse/.style={{
    dash dot, line width=0.85pt, mark=none, forget plot,
  }},
  rsum snr/unq/.style={{
    solid, line width=0.9pt, mark=none, forget plot,
  }},
  rsum snr/one/.style={{mark=*, mark size=1.85pt}},
  rsum snr/two/.style={{mark=square*, mark size=1.8pt}},
  rsum snr/three/.style={{mark=triangle*, mark size=2.4pt}},
}}
\begin{{groupplot}}[
  group style={{group name=rsumsnr, group size=3 by 1, horizontal sep=1.05cm}},
  scale only axis, width=4.55cm, height=4.4cm,
  axis lines=left, axis line style={{draw=snrInk, line width=0.45pt, -}},
  tick align=outside, tick pos=left,
  major tick length=2.5pt, tick style={{draw=snrInk, line width=0.45pt}},
  ymajorgrids=true, xmajorgrids=false,
  grid style={{line width=0.3pt, draw=snrGrid}},
  every axis plot/.append style={{line join=round, mark repeat=2, mark phase=1}},
  title style={{font=\small, yshift=2pt}},
  tick label style={{font=\footnotesize, /pgf/number format/fixed}},
  label style={{font=\small}},
  xmin=-12, xmax=32, xtick={{-10,0,10,20,30}},
  xlabel={{SNR [dB]}}, ymin=0,
]
"""
BCOL = {1: 'snrOne', 2: 'snrTwo', 3: 'snrThree'}
BSTY = {1: 'one', 2: 'two', 3: 'three'}
BTXT = {1: '1 bit', 2: '2 bits', 3: '3 bits'}
SNR_PANELS = [(2, '(a) $K=2$', 26, [0, 5, 10, 15, 20, 25]), (4, '(b) $K=4$', 46, [0, 10, 20, 30, 40]),
              (6, '(c) $K=6$', 66, [0, 20, 40, 60])]


def _tab(vals):
    return 'table {%\n' + '\n'.join(f'{x:g} {v:.4f}' for x, v in zip(SNR, vals) if x >= -10) + '\n};'


def fig_snr(data, out):
    L = [SNR_HEAD.format(ls=LS_NOTE).rstrip('\n')]
    for i, (K, title, ymax, yt) in enumerate(SNR_PANELS):
        opts = [f'title={{{title}}}', f'ymax={ymax}', 'ytick={' + ','.join(map(str, yt)) + '}']
        if i == 0:
            opts += [r'ylabel={$R_{\mathrm{sum}}$ [bits/channel use]}', 'legend to name=rsumsnrlegend',
                     'legend columns=3', 'legend cell align=left',
                     'legend style={\n    draw=none, fill=none, font=\\footnotesize,\n'
                     '    /tikz/every even column/.append style={column sep=0.55cm},\n  }']
        L.append(r'\nextgroupplot[' + ('\n  ' + ',\n  '.join(opts) + ',\n]' if i == 0 else ', '.join(opts) + ']'))
        if i == 0:
            for b in (1, 2, 3):
                L += [r'\addlegendimage{%s, rsum snr/gnn, rsum snr/%s}' % (BCOL[b], BSTY[b]),
                      r'\addlegendentry{GNN, %s}' % BTXT[b]]
            for b in (1, 2, 3):
                L += [r'\addlegendimage{%s!55!snrMuted, rsum snr/zf, rsum snr/%s}' % (BCOL[b], BSTY[b]),
                      r'\addlegendentry{ZF + DAC, %s}' % BTXT[b]]
            for b in (1, 2, 3):
                L += [r'\addlegendimage{%s!55!snrMuted, rsum snr/wmmse}' % BCOL[b],
                      r'\addlegendentry{WMMSE + DAC, %s}' % BTXT[b]]
            L += [r'\addlegendimage{snrInk, rsum snr/unq}', r'\addlegendentry{Unquantized WMMSE}']
        L.append(r'\addplot[snrInk, rsum snr/unq] %s' % _tab(data[(K, 1)]['wmmse_unq']))
        for b in (1, 2, 3):
            L.append(r'\addplot[%s!55!snrMuted, rsum snr/wmmse] %s' % (BCOL[b], _tab(data[(K, b)]['wmmse_q'])))
        for b in (1, 2, 3):
            L.append(r'\addplot[%s!55!snrMuted, rsum snr/zf, rsum snr/%s] %s' % (BCOL[b], BSTY[b], _tab(data[(K, b)]['lin_q'])))
        for b in (1, 2, 3):
            L.append(r'\addplot[%s, rsum snr/gnn, rsum snr/%s] %s' % (BCOL[b], BSTY[b], _tab(data[(K, b)]['gnn'])))
    L += [r'\end{groupplot}', r'\node[anchor=south] at ($(rsumsnr c2r1.north)+(0,0.65cm)$)',
          r'  {\pgfplotslegendfromname{rsumsnrlegend}};', r'\end{tikzpicture}', r'\end{document}', '']
    open(out, 'w').write('\n'.join(L))


# -------------------------------------------------------------------------------------------- preview
def preview(data, out):
    kc = {1: '#0072B2', 2: '#D55E00', 4: '#009E73', 6: '#A35D94'}
    bc = {1: '#0072B2', 2: '#009E73', 3: '#D55E00'}
    bm = {1: 'o', 2: 's', 3: '^'}
    mute = lambda h: tuple(0.55 * int(h[i:i + 2], 16) / 255 + 0.45 * int('9BA3AB'[i - 1:i + 1], 16) / 255 for i in (1, 3, 5))
    fig = plt.figure(figsize=(12, 8.6))
    gs = fig.add_gridspec(2, 6, height_ratios=[1, 1.05], hspace=0.95, wspace=0.9)
    for j, (Ks, title, ymax) in enumerate((((1, 2), '(a) $K=1,2$', 21), ((4, 6), '(b) $K=4,6$', 51))):
        a = fig.add_subplot(gs[0, 3 * j:3 * j + 3])
        a.axvspan(3.65, 4.65, color='0.97'); a.axvline(3.65, color='0.8', ls='--', lw=0.6)
        for K in Ks:
            c = kc[K]; bs = [1, 2, 3]
            a.plot(bs, [data[(K, b)]['lin_q'][I20] for b in bs], ls=':', color=c, marker='s', mfc='white', lw=1.3)
            if K > 1:
                a.plot(bs, [data[(K, b)]['wmmse_q'][I20] for b in bs], ls='-.', color=c, marker='p', mfc='white', lw=1.3)
            a.plot(bs, [data[(K, b)]['gnn'][I20] for b in bs], ls='-', color=c, marker='o', lw=1.3)
            a.plot(bs, [data[(K, b)]['gd'][I20] for b in bs], ls='--', color=c, marker='^', mfc='white', lw=1.3)
            a.plot([X_UNQ_LIN], [data[(K, 1)]['lin_unq'][I20]], 'D', color=c)
            if K > 1:
                a.plot([X_UNQ_WMMSE], [data[(K, 1)]['wmmse_unq'][I20]], 'p', color=c, ms=8)
            a.text(3.05, data[(K, 3)]['gd'][I20], f'$K={K}$', color=c, va='center', fontsize=8)
        if 1 in Ks:
            a.text(0.02, 0.97, '$K=1$: WMMSE $\\equiv$ MRT', transform=a.transAxes, va='top', fontsize=7.5, color='#42484F')
        a.set_xlim(0.8, 4.65); a.set_ylim(0, ymax); a.set_xticks([1, 2, 3, 4.2]); a.set_xticklabels(['1', '2', '3', '$\\infty$'])
        a.set_title(title, fontsize=10); a.set_xlabel('DAC resolution $b$ [bits]', fontsize=9); a.grid(axis='y', color='#E2E5E8')
        if j == 0: a.set_ylabel('$R_{sum}$ [bits/channel use]', fontsize=9)
    from matplotlib.lines import Line2D
    ink = '#42484F'
    hb = [Line2D([], [], color=ink, marker='o'), Line2D([], [], color=ink, ls='-.', marker='p', mfc='white'),
          Line2D([], [], color=ink, ls='none', marker='p', ms=8), Line2D([], [], color=ink, ls='--', marker='^', mfc='white'),
          Line2D([], [], color=ink, ls=':', marker='s', mfc='white'), Line2D([], [], color=ink, ls='none', marker='D')]
    lb = ['GNN', 'WMMSE + DAC', 'Unquantized WMMSE', 'GNN-GD', 'ZF/MRT + DAC', 'Unquantized ZF/MRT']
    fig.legend([hb[i] for i in (0, 3, 1, 4, 2, 5)], [lb[i] for i in (0, 3, 1, 4, 2, 5)], loc='upper center', ncol=3,
               fontsize=8, frameon=False, bbox_to_anchor=(0.5, 0.995))
    for j, (K, title, ymax, yt) in enumerate(SNR_PANELS):
        a = fig.add_subplot(gs[1, 2 * j:2 * j + 2])
        xs = SNR_PLOT; cut = SNR.index(-10.0)
        a.plot(xs, data[(K, 1)]['wmmse_unq'][cut:], color=ink, lw=1.2)
        for b in (1, 2, 3):
            a.plot(xs, data[(K, b)]['wmmse_q'][cut:], ls='-.', color=mute(bc[b]), lw=1.1)
            a.plot(xs, data[(K, b)]['lin_q'][cut:], ls='--', color=mute(bc[b]), marker=bm[b], mfc='white', markevery=2, lw=1.1)
            a.plot(xs, data[(K, b)]['gnn'][cut:], color=bc[b], marker=bm[b], markevery=2, lw=1.5)
        a.set_ylim(0, ymax); a.set_yticks(yt); a.set_xlim(-12, 32); a.set_xticks([-10, 0, 10, 20, 30])
        a.set_title(title, fontsize=10); a.set_xlabel('SNR [dB]', fontsize=9); a.grid(axis='y', color='#E2E5E8')
        if j == 0: a.set_ylabel('$R_{sum}$ [bits/channel use]', fontsize=9)
    row2_top = max(ax.get_position().y1 for ax in fig.axes[2:])
    hs, ls_ = [], []
    for kind in ('gnn', 'zf', 'wmmse'):
        for b in (1, 2, 3):
            if kind == 'gnn': hs.append(Line2D([], [], color=bc[b], marker=bm[b])); ls_.append(f'GNN, {BTXT[b]}')
            elif kind == 'zf': hs.append(Line2D([], [], color=mute(bc[b]), ls='--', marker=bm[b], mfc='white')); ls_.append(f'ZF + DAC, {BTXT[b]}')
            else: hs.append(Line2D([], [], color=mute(bc[b]), ls='-.')); ls_.append(f'WMMSE + DAC, {BTXT[b]}')
    hs.append(Line2D([], [], color=ink)); ls_.append('Unquantized WMMSE')
    fig.legend(hs, ls_, loc='lower center', ncol=3, fontsize=7.5, frameon=False, bbox_to_anchor=(0.5, row2_top + 0.035))
    fig.savefig(out, dpi=130, bbox_inches='tight')


def main():
    data = load()
    fig_bits(data, os.path.join(CONT, 'Rsum_sweep_vs_bits.tex'))
    fig_snr(data, os.path.join(CONT, 'Rsum_sweep_vs_snr.tex'))
    preview(data, os.path.join(CONT, 'preview_continue_figures.png'))
    print('wrote Rsum_sweep_vs_bits.tex, Rsum_sweep_vs_snr.tex, preview_continue_figures.png in', CONT)


if __name__ == '__main__':
    main()
