"""Write Figure/ber_<mod>_20dB.tex (pgfplots, style of the paper's other figures) from exp_results/ber_<mod>_20dB.json.

Three panels, one per DAC resolution b; x: number of UEs K; y: uncoded BER at 20 dB (log scale).
GNN, IDE with beta_WF and IDE with block beta (each if present in the json) for every b, SQUID for b = 1 only.

  python plot_ber_qpsk.py [qpsk|16qam] [path/to/Figure]      # default: qpsk
"""
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = sys.argv[1] if len(sys.argv) > 1 else 'qpsk'
MOD_NAME = {'qpsk': 'QPSK', '16qam': 'Gray 16-QAM'}[MOD]
SRC = os.path.join(HERE, 'exp_results', f'ber_{MOD}_20dB.json')
DST = sys.argv[2] if len(sys.argv) > 2 else '/home/user/Quantized-aware-training-and-deploy-study/Figure'
KS = (1, 2, 4, 6)
IDE_SERIES = (('ide_wf', 'ber/ide', r'IDE, $\beta_{\mathrm{WF}}$'),       # both variants shown (user, 2026-09-29)
              ('ide_block', 'ber/ideblk', r'IDE, block $\beta$'))

HEAD = r"""%% Uncoded BER with %(mod)s signaling at SNR = 20 dB versus the number of UEs K, M = 40.
%% (a) b = 1: GNN, IDE (beta_WF, block beta), SQUID; (b) b = 2 and (c) b = 3: GNN, IDE (beta_WF, block beta).
%% Source: exp_results/ber_%(tag)s_20dB.json (ber_%(tag)s_20dB.py): 2048 held-out channels, 125 symbols each,
%% per-block effective-gain equalization, BER exact with respect to the AWGN.
%% Generated by plot_ber_qpsk.py %(tag)s.
\documentclass[tikz,border=4pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{newtxtext,newtxmath}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepgfplotslibrary{groupplots}
\usetikzlibrary{calc}
\begin{document}
\definecolor{berGNN}{HTML}{0072B2}
\definecolor{berIDE}{HTML}{D55E00}
\definecolor{berSQUID}{HTML}{009E73}
\definecolor{berIDEb}{HTML}{CC79A7}
\definecolor{berGrid}{HTML}{E2E5E8}
\definecolor{berInk}{HTML}{42484F}
\begin{tikzpicture}
\pgfplotsset{
  ber/gnn/.style={berGNN, solid, line width=1.1pt, mark=*, mark size=2.1pt, mark options={solid}},
  ber/ide/.style={berIDE, dashed, line width=1.0pt, mark=square*, mark size=2.0pt,
    mark options={solid, fill=white}},
  ber/ideblk/.style={berIDEb, densely dotted, line width=1.1pt, mark=diamond*, mark size=2.7pt,
    mark options={solid, fill=white}},
  ber/squid/.style={berSQUID, dash dot, line width=1.0pt, mark=triangle*, mark size=2.6pt,
    mark options={solid, fill=white}},
}
\begin{groupplot}[
  group style={group name=berplots, group size=3 by 1, horizontal sep=1.1cm},
  scale only axis, width=4.5cm, height=4.2cm,
  ymode=log, ymin=%(ymin)s, ymax=%(ymax)s,
  axis lines=left, axis line style={draw=berInk, line width=0.45pt, -},
  tick align=outside, tick pos=left,
  major tick length=2.5pt, tick style={draw=berInk, line width=0.45pt},
  ymajorgrids=true, grid style={line width=0.3pt, draw=berGrid},
  title style={font=\small, yshift=2pt},
  tick label style={font=\footnotesize},
  label style={font=\small},
  xmin=0.5, xmax=6.5, xtick={1,2,4,6},
  xlabel={Number of UEs $K$},
]
"""


def table(vals):
    return 'coordinates {' + ' '.join(f'({k},{v:.4e})' for k, v in zip(KS, vals)) + '};'


def main():
    res = json.load(open(SRC))['results']
    get = lambda key, b: [res[f'K{k}b{b}'][key] for k in KS]          # noqa: E731
    ides = [x for x in IDE_SERIES if all(x[0] in r for r in res.values())]
    allv = [v for b in (1, 2, 3) for key in ['gnn'] + [x[0] for x in ides] for v in get(key, b)] + get('squid', 1)
    lo = 10 ** math.floor(math.log10(max(min(allv), 1e-12)) - 0.3)
    hi = 10 ** math.ceil(math.log10(max(allv)) + 0.1)
    L = [HEAD % {'ymin': f'{lo:.0e}', 'ymax': f'{min(hi, 1.0):.0e}', 'mod': MOD_NAME, 'tag': MOD}]
    for i, b in enumerate((1, 2, 3)):
        opts = [f'title={{({"abc"[i]}) $b={b}$}}']
        if i == 0:
            opts += [r'ylabel={Uncoded BER}', 'legend to name=berlegend', f'legend columns={2 + len(ides)}',
                     'legend cell align=left',
                     'legend style={draw=none, fill=none, font=\\footnotesize, '
                     '/tikz/every even column/.append style={column sep=0.5cm}}']
        L.append(r'\nextgroupplot[' + ', '.join(opts) + ']')
        if i == 0:
            L += [r'\addlegendimage{ber/gnn}', r'\addlegendentry{GNN (proposed)}',
                  *[e for _, st, lab in ides for e in (rf'\addlegendimage{{{st}}}', rf'\addlegendentry{{{lab}}}')],
                  r'\addlegendimage{ber/squid}', r'\addlegendentry{SQUID ($b=1$ only)}']
        for key, st, _ in ides:
            L.append(rf'\addplot[{st}, forget plot] ' + table(get(key, b)))
        if b == 1:
            L.append(r'\addplot[ber/squid, forget plot] ' + table(get('squid', b)))
        L.append(r'\addplot[ber/gnn, forget plot] ' + table(get('gnn', b)))
    L += [r'\end{groupplot}', r'\node[anchor=south] at ($(berplots c2r1.north)+(0,0.75cm)$)',
          r'  {\pgfplotslegendfromname{berlegend}};', r'\end{tikzpicture}', r'\end{document}', '']
    path = os.path.join(DST, f'ber_{MOD}_20dB.tex')
    open(path, 'w').write('\n'.join(L))
    print('wrote', path)


if __name__ == '__main__':
    main()
